version: '1'

services:
  app:
    image: 'tets:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: testForSk
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test